name: Resolve yarn.lock (test fix)

on:
  issue_comment:
    types: [created]

jobs:
  resolve-yarn-lock-on-comment-fix:
    name: '/'
    if: contains(github.event.comment.body, '/resolve-test yarn.lock')
    secrets: inherit
    with:
      pr_number: ${{ github.event.issue.number }}
      repo: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c # v1
        id: get-token
        with:
          app-id: ${{ secrets.TXO_GITHUB_BOT_APP_ID }}
          private-key: ${{ secrets.TXO_GITHUB_BOT_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          token: ${{ steps.get-token.outputs.token }}

      - name: Get PR branch names
        env:
          REPO: ${{ inputs.repo }}
          PR_NO: ${{ inputs.pr_number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "HEAD_BRANCH=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> $GITHUB_ENV
          echo "BASE_BRANCH=$(gh pr view $PR_NO --repo $REPO --json baseRefName --jq '.baseRefName')" >> $GITHUB_ENV

      - name: Checkout PR branch and merge base branch
        run: |
          git config --global user.email "txo-github-bot[bot]@users.noreply.github.com"
          git config --global user.name "TXO GitHub Bot[bot]"
          git fetch origin ${{ env.BASE_BRANCH }}
          git fetch origin ${{ env.HEAD_BRANCH }}
          git checkout ${{ env.BASE_BRANCH }}
          git pull
          git checkout ${{ env.HEAD_BRANCH }}
          git pull
          git merge ${{ env.BASE_BRANCH }} || true

      - name: Check for merge conflict on yarn.lock file
        run: |
          YARN_LOCK_HAS_CONFLICTS=$(git ls-files -u | grep yarn.lock | wc -l)
          echo "YARN_LOCK_HAS_CONFLICTS=$YARN_LOCK_HAS_CONFLICTS" >> $GITHUB_ENV

      - name: Run yarn install to resolve conflicts automatically
        if: env.YARN_LOCK_HAS_CONFLICTS > 0
        run: |
          yarn install

      # - name: Commit yarn.lock
      #   run: |
      #     git add yarn.lock
      #     git commit -m "chore: resolve yarn.lock"

      # - name: Push yarn.lock
      #   run: |
      #     git push
